# Generated by Django 3.2.4 on 2021-06-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210630_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Total de donaciones',
                'verbose_name_plural': 'Total de donaciones',
            },
        ),
    ]
